"""Mock parser used to verify the Parser-to-Document pipeline."""

from pathlib import Path

from src.models.block import Block, BlockType
from src.models.document import Document
from src.models.metadata import Metadata, SourceReference
from src.models.page import Page

from .base import BaseParser


class MockParser(BaseParser):
    """Return deterministic document data without reading the input file."""

    parser_name = "mock-parser"
    parser_version = "1.0"

    def parse(self, file_path: str | Path) -> Document:
        path = Path(file_path)
        filename = path.name
        file_type = path.suffix.lower().lstrip(".") or "unknown"
        document_id = f"mock:{filename}"

        title_block_id = "mock-title-1"
        text_block_id = "mock-text-1"
        title_source = SourceReference(
            document_id=document_id,
            page_number=1,
            source_id=title_block_id,
        )
        text_source = SourceReference(
            document_id=document_id,
            page_number=1,
            source_id=text_block_id,
        )

        return Document(
            document_id=document_id,
            filename=filename,
            file_type=file_type,
            metadata=Metadata(
                original_filename=filename,
                parser_name=self.parser_name,
                parser_version=self.parser_version,
            ),
            pages=[
                Page(
                    page_number=1,
                    blocks=[
                        Block(
                            block_id=title_block_id,
                            type=BlockType.TITLE,
                            content="Mock Parsed Document",
                            page_number=1,
                            source=title_source,
                        ),
                        Block(
                            block_id=text_block_id,
                            type=BlockType.TEXT,
                            content="This document was generated by MockParser",
                            page_number=1,
                            source=text_source,
                        ),
                    ],
                )
            ],
        )
